"""empty message

Revision ID: 133c716ee8ea
Revises: 97c69e9fc3d9
Create Date: 2024-02-18 02:30:45.540383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '133c716ee8ea'
down_revision: Union[str, None] = '97c69e9fc3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Integer(), nullable=False),
    sa.Column('caption_1', sa.Integer(), nullable=False),
    sa.Column('caption_2', sa.Integer(), nullable=False),
    sa.Column('name_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('one_is_better', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparison')
    # ### end Alembic commands ###
