# fly.toml app configuration file generated for yorknew-summer-firefly-8063 on 2024-02-17T23:52:09-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yorknew'
primary_region = 'sjc'

[build.args]
API_URL = "https://yorknew.fly.dev"

[env]
  REFLEX_DB = 'sqlite:////data/reflex.db'

[[mounts]]
  source = 'yorknew_data'
  destination = '/data'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
